FROM gradle:8.1.1-jdk17 AS build
COPY  . /home/gradle/src
WORKDIR /home/gradle/src
ARG github_username
ARG github_token
ENV GITHUB_USERNAME $github_username
ENV GITHUB_TOKEN $github_token
RUN gradle assemble

FROM amazoncorretto:17-alpine3.14
EXPOSE 8080
RUN mkdir /app
COPY --from=build /home/gradle/src/build/libs/*.jar /app/
ENTRYPOINT ["java", "-jar", "-Dspring.profiles.active=dev","/app/linter-0.0.1-SNAPSHOT.jar"]