# redis host and port parameters
redis:
  host: redis
  port: 6379

# streamKeys to be used by producers
stream:
  created-key: "snippet-linting-stream"
  updated-key: "linting-updated-stream"


# groupIds to be used by consumers
groups:
  product: "snippet-linter-group"

auth0:
  audience: snippet-authorizer


spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://snippet-authorizer.us.auth0.com/

logging:
  level:
    org:
      springframework:
        security: DEBUG
